### ISSUE TITLE
How to avoid hitting quad tree error?

### ISSUE THREAD

**Issue by tom-osint** [graphology/graphology#359] opened 2022-02-09 00:46 UTC
I'm visualising a large dataset and I'm currently using circular to initially set the node positions, before using fa2.
However sometimes the graph decides to spit out an error, which breaks the entire graph.
The error is "sigma/quadtree.insertNode: At least 5 nodes are outside the global quadtree zone. You might have a problem with the normalization function or the custom bounding box."

Unsure how to mitigate this.

**Comment by Yomguithereal** [comment] 2022-02-09 09:28
Hello @tom-osint, this is an issue with sigma, not graphology so I will close it. 

> Unsure how to mitigate this.

Are you using a custom bounding box or normalization? Else you will need to provide a minimal reproducible example on a sigma issue because we can't really help you without it.

**Closed by Yomguithereal** 2022-02-09 09:28 UTC
